### ISSUE TITLE
`opta version` command failed

### ISSUE THREAD

**Issue by anmyachev** [run-x/opta#625]
#### What happened:

```
$ .opta/opta version
[3335] Error loading Python lib '/home/ec2-user/.opta/libpython3.8.so.1.0': dlopen: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /home/ec2-user/.opta/libpython3.8.so.1.0)
```

#### How to reproduce it (as minimally and precisely as possible):

`/bin/bash -c "$(curl -fsSL https://docs.opta.dev/install.sh)"`

#### Environment:
- Opta version (use `opta version`): `failed`
- Cloud provider (or hardware configuration for local): `AWS`
- OS (e.g: `cat /etc/os-release`): 
```bash
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
- Kernel (e.g. `uname -a`): `Linux ip-172-31-89-70.ec2.internal 5.10.93-87.444.amzn2.x86_64 #1 SMP Thu Jan 20 22:50:50 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:

**Comment by juandiegopalomino** [comment]
@anmyachev thank you so much for creating the issue, and sorry for the delay. We have been able to reproduce and it looks like it's because of a dependency on a an ewer version of GLIBC which Amazon Linux does not have by default. We'll keep you notified once we reach a solution.

**Comment by juandiegopalomino** [comment]
@anmyachev hey, thanks again for raising this issue!

Long story short, Opta did not support Centos or Amazon Linux because of what seems to be an older version of GLIBC which they run (although that could've just been the tip of the ice berg). Because of your ask, we're starting to support those :). We've been working hard today for a new packaging pipeline and installation scripts for this new support. Please expect it within a day or so-- I'll comment again once it's fully ready.

**Comment by NitinAgg** [comment]
Hi @anmyachev, I just released a alpha binary for amazon linux. You can install this version on amazon linux using this command 

`VERSION=0.24.4 /bin/bash -c "$(curl -fsSL https://docs.opta.dev/install.sh)"`

**Comment by juandiegopalomino** [comment]
Confirmed it works on amazon linux
